/* Cable: CMake Bootstrap Library.
 * Copyright 2019 Pawel Bylica.
 * Licensed under the Apache License, Version 2.0.
 */

/* Generated by Cable Build Info on 2020-11-23T09:41:02. Do not modify directly. */

#pragma once

#define ALETH_VERSION "1.8.0+commit.af7b28a0.dirty"

#ifdef __cplusplus
constexpr auto aleth_version = "1.8.0+commit.af7b28a0.dirty";
#endif
